# Site settings
title: anirudh24seven
email: anirudh24seven [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and rants by anirudh24seven
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anirudh24seven.github.io/" # the base hostname & protocol for your site
twitter_username: anirudh24seven
github_username:  anirudh24seven

# Build settings
markdown: kramdown
